# Generated by Django 5.1.3 on 2024-12-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_permissionhelper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermissionHelper',
            new_name='PermissionHelperModel',
        ),
    ]
