# Generated by Django 5.1.3 on 2024-12-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_rename_permissionhelper_permissionhelpermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemodel',
            name='users',
        ),
    ]
